# Задание №1. NumPy

Данны массивы:

*   prices = np.array([1200, 800, 2500, 3100, 450, 1800])
*   counts = np.array([2, 1, 3, 1, 5, 2])

Выполните:
1. получите массив стоимости каждой позиции: price * count;
2. найдите общую стоимость всех позиций;
3. найдите среднюю цену;
4. получите только цены больше 1500;
5. получите цены от 1000 до 3000 включительно;
6. посчитайте количество цен больше 1500.

In [52]:
import numpy as np

prices = np.array([1200, 800, 2500, 3100, 450, 1800])
counts = np.array([2, 1, 3, 1, 5, 2])

In [53]:
## получите массив стоимости каждой позиции: price * count;
print(prices * counts)

[2400  800 7500 3100 2250 3600]

In [54]:
## найдите общую стоимость всех позиций;
print(sum(prices * counts))

19650

In [55]:
## найдите среднюю цену;
print(np.mean(prices))

1641.6666666666667

In [56]:
## получите только цены больше 1500;
print(prices[prices >=1500])

[2500 3100 1800]

In [57]:
## получите цены от 1000 до 3000 включительно;
print(prices[(prices >= 1000) & (prices <= 3000)])

[1200 2500 1800]

In [58]:
## посчитайте количество цен больше 1500.
print(len(prices[prices > 1500]))

3

# Задание №2. Загрузка и первичный осмотр

Загрузите hw2_orders.csv в DataFrame.

Загрузите и получите:
1. тип объекта;
2. количество строк и столбцов;
3. названия столбцов;
4. типы данных;
5. первые 5 строк;
6. последние 3 строки;
7. info();
8. describe().

In [59]:
import pandas as pd

orders = pd.read_csv("hw2_orders.csv")

orders

,order_id,customer,city,category,amount,status,delivery_days,rating
0,2001,Дарья Мельникова,Москва,tech,3490,paid,2,5
1,2002,Илья Воронов,Казань,books,990,paid,5,4
2,2003,Полина Жукова,Самара,office,650,paid,4,4
3,2004,Артур Беляев,Москва,home,2290,paid,3,5
4,2005,Елена Фомина,Санкт-Петербург,tech,4890,cancelled,0,0
5,2006,Кирилл Громов,Казань,home,1750,paid,6,3
6,2007,Валерия Тихонова,Москва,books,1350,paid,2,5
7,2008,Олег Комаров,Самара,tech,5790,paid,3,4
8,2009,Анастасия Савельева,Санкт-Петербург,office,870,paid,4,4
9,2010,Глеб Макаров,Москва,tech,2600,paid,1,5
10,2011,Марина Алексеева,Казань,office,540,cancelled,0,0
11,2012,Степан Захаров,Самара,home,1980,paid,5,4
12,2013,Ксения Миронова,Москва,tech,7200,paid,2,5
13,2014,Евгений Романов,Санкт-Петербург,books,1480,paid,3,4
14,2015,Людмила Баранова,Казань,tech,3150,paid,4,4
15,2016,Матвей Соловьёв,Москва,office,760,paid,3,3
16,2017,Вероника Власова,Самара,books,1120,paid,6,5
17,2018,Денис Куликов,Санкт-Петербург,home,2840,cancelled,0,0
18,2019,Татьяна Фролова,Москва,home,1940,paid,2,4
19,2020,Павел Казаков,Казань,tech,4250,paid,3,5
20,2021,Арина Маслова,Самара,office,920,paid,4,4
21,2022,Владимир Гусев,Москва,books,1680,paid,5,4
22,2023,Маргарита Орехова,Санкт-Петербург,tech,5350,paid,2,5
23,2024,Антон Быков,Казань,home,2050,paid,4,3
24,2025,Нина Данилова,Москва,office,610,cancelled,0,0
25,2026,Ярослав Крылов,Самара,tech,3800,paid,3,4
26,2027,Алёна Зайцева,Санкт-Петербург,books,1250,paid,5,5
27,2028,Борис Мартынов,Москва,home,2470,paid,2,4
28,2029,Оксана Котова,Казань,office,830,paid,6,4
29,2030,Фёдор Суворов,Самара,tech,6400,paid,1,5

In [60]:
## тип объекта
print(orders['category'].dtypes)

object

In [61]:
## кол-во строк и столбцов
orders.shape

(30, 8)

In [62]:
## название столбцов
orders.columns

Index(['order_id', 'customer', 'city', 'category', 'amount', 'status',
       'delivery_days', 'rating'],
      dtype='object')

In [63]:
## типы данных
orders.dtypes

order_id          int64
customer         object
city             object
category         object
amount            int64
status           object
delivery_days     int64
rating            int64
dtype: object

In [64]:
## первые 5 строк
orders.head()

,order_id,customer,city,category,amount,status,delivery_days,rating
0,2001,Дарья Мельникова,Москва,tech,3490,paid,2,5
1,2002,Илья Воронов,Казань,books,990,paid,5,4
2,2003,Полина Жукова,Самара,office,650,paid,4,4
3,2004,Артур Беляев,Москва,home,2290,paid,3,5
4,2005,Елена Фомина,Санкт-Петербург,tech,4890,cancelled,0,0

In [65]:
## последние 3 строки
orders.tail(3)

,order_id,customer,city,category,amount,status,delivery_days,rating
27,2028,Борис Мартынов,Москва,home,2470,paid,2,4
28,2029,Оксана Котова,Казань,office,830,paid,6,4
29,2030,Фёдор Суворов,Самара,tech,6400,paid,1,5

In [66]:
## info()
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       30 non-null     int64
 1   customer       30 non-null     object
 2   city           30 non-null     object
 3   category       30 non-null     object
 4   amount         30 non-null     int64
 5   status         30 non-null     object
 6   delivery_days  30 non-null     int64
 7   rating         30 non-null     int64
dtypes: int64(4), object(4)
memory usage: 2.0+ KB

In [67]:
## describe()
orders.describe()

          order_id       amount  delivery_days     rating
count    30.000000    30.000000       30.00000  30.000000
mean   2015.500000  2509.666667        3.00000   3.700000
std       8.803408  1858.984675        1.83829   1.600646
min    2001.000000   540.000000        0.00000   0.000000
25%    2008.250000  1022.500000        2.00000   4.000000
50%    2015.500000  1960.000000        3.00000   4.000000
75%    2022.750000  3405.000000        4.00000   5.000000
max    2030.000000  7200.000000        6.00000   5.000000

*Какие столбцы являются числовыми? Какие столбцы содержат категориальные значения?*

Категориальные значени столбцы: customer, city, category, status  

Числовые значения столбцы: order_id, amount, delivery_days, rating

# Задание 3. Выбор и фильтрация

## 3.1 Выбор столбцов
Получите:

1. столбец amount как Series;
2. новый DataFrame только со столбцами:
customer,
city,
category,
amount

In [68]:
amounts = orders['amount']

amounts

0     3490
1      990
2      650
3     2290
4     4890
5     1750
6     1350
7     5790
8      870
9     2600
10     540
11    1980
12    7200
13    1480
14    3150
15     760
16    1120
17    2840
18    1940
19    4250
20     920
21    1680
22    5350
23    2050
24     610
25    3800
26    1250
27    2470
28     830
29    6400
Name: amount, dtype: int64

In [69]:
short_orders = orders[['customer','city','category','amount']]

short_orders

               customer             city category  amount
0      Дарья Мельникова           Москва     tech    3490
1          Илья Воронов           Казань    books     990
2         Полина Жукова           Самара   office     650
3          Артур Беляев           Москва     home    2290
4          Елена Фомина  Санкт-Петербург     tech    4890
5         Кирилл Громов           Казань     home    1750
6      Валерия Тихонова           Москва    books    1350
7          Олег Комаров           Самара     tech    5790
8   Анастасия Савельева  Санкт-Петербург   office     870
9          Глеб Макаров           Москва     tech    2600
10     Марина Алексеева           Казань   office     540
11       Степан Захаров           Самара     home    1980
12      Ксения Миронова           Москва     tech    7200
13      Евгений Романов  Санкт-Петербург    books    1480
14     Людмила Баранова           Казань     tech    3150
15      Матвей Соловьёв           Москва   office     760
16     Вероника Власова           Самара    books    1120
17        Денис Куликов  Санкт-Петербург     home    2840
18      Татьяна Фролова           Москва     home    1940
19        Павел Казаков           Казань     tech    4250
20        Арина Маслова           Самара   office     920
21       Владимир Гусев           Москва    books    1680
22    Маргарита Орехова  Санкт-Петербург     tech    5350
23          Антон Быков           Казань     home    2050
24        Нина Данилова           Москва   office     610
25       Ярослав Крылов           Самара     tech    3800
26        Алёна Зайцева  Санкт-Петербург    books    1250
27       Борис Мартынов           Москва     home    2470
28        Оксана Котова           Казань   office     830
29        Фёдор Суворов           Самара     tech    6400

## 3.2 Один фильтр
Получите:

1. только оплаченные заказы;
2. только заказы из Москвы;
3. только заказы дороже 3000;
4. только заказы с рейтингом 5.

In [70]:
## я не очень понял нужно было раздельно для каждого пункта писать фильтр или же одним условием, написал так:

filter_orders_320 = orders[
    (orders['status'] == 'paid')
    & (orders['city'] == 'Москва')
    & (orders['amount'] >= 3000)
    &(orders['rating'] == 5)]

filter_orders_320

,order_id,customer,city,category,amount,status,delivery_days,rating
0,2001,Дарья Мельникова,Москва,tech,3490,paid,2,5
12,2013,Ксения Миронова,Москва,tech,7200,paid,2,5

## 3.3 Несколько условий
Получите:

1. оплаченные московские заказы дороже 2000;
2. заказы из Казани или Самары;
3. заказы категории tech с рейтингом 5.

In [71]:
#москва оплачены дороже 2000

filter_orders_331 = orders[
     (orders['city'] == 'Москва')
     & (orders['status'] == 'paid')
     & (orders['amount'] >= 2000)
]

filter_orders_331

,order_id,customer,city,category,amount,status,delivery_days,rating
0,2001,Дарья Мельникова,Москва,tech,3490,paid,2,5
3,2004,Артур Беляев,Москва,home,2290,paid,3,5
9,2010,Глеб Макаров,Москва,tech,2600,paid,1,5
12,2013,Ксения Миронова,Москва,tech,7200,paid,2,5
27,2028,Борис Мартынов,Москва,home,2470,paid,2,4

In [72]:
## Казань или Самара

filter_orders_332 = orders[
    (orders['city'] == 'Казань') | (orders['city'] == 'Самара')
]

filter_orders_332

,order_id,customer,city,category,amount,status,delivery_days,rating
1,2002,Илья Воронов,Казань,books,990,paid,5,4
2,2003,Полина Жукова,Самара,office,650,paid,4,4
5,2006,Кирилл Громов,Казань,home,1750,paid,6,3
7,2008,Олег Комаров,Самара,tech,5790,paid,3,4
10,2011,Марина Алексеева,Казань,office,540,cancelled,0,0
11,2012,Степан Захаров,Самара,home,1980,paid,5,4
14,2015,Людмила Баранова,Казань,tech,3150,paid,4,4
16,2017,Вероника Власова,Самара,books,1120,paid,6,5
19,2020,Павел Казаков,Казань,tech,4250,paid,3,5
20,2021,Арина Маслова,Самара,office,920,paid,4,4
23,2024,Антон Быков,Казань,home,2050,paid,4,3
25,2026,Ярослав Крылов,Самара,tech,3800,paid,3,4
28,2029,Оксана Котова,Казань,office,830,paid,6,4
29,2030,Фёдор Суворов,Самара,tech,6400,paid,1,5

## 3.4 isin() и between()
Одним выражением выберите заказы, для которых:

* город — Москва, Казань или Санкт-Петербург;
* сумма заказа от 1500 до 4000 включительно.

In [73]:
orders[orders['city'].isin(['Москва','Казань','Санкт-Петербург'])]

,order_id,customer,city,category,amount,status,delivery_days,rating
0,2001,Дарья Мельникова,Москва,tech,3490,paid,2,5
1,2002,Илья Воронов,Казань,books,990,paid,5,4
3,2004,Артур Беляев,Москва,home,2290,paid,3,5
4,2005,Елена Фомина,Санкт-Петербург,tech,4890,cancelled,0,0
5,2006,Кирилл Громов,Казань,home,1750,paid,6,3
6,2007,Валерия Тихонова,Москва,books,1350,paid,2,5
8,2009,Анастасия Савельева,Санкт-Петербург,office,870,paid,4,4
9,2010,Глеб Макаров,Москва,tech,2600,paid,1,5
10,2011,Марина Алексеева,Казань,office,540,cancelled,0,0
12,2013,Ксения Миронова,Москва,tech,7200,paid,2,5
13,2014,Евгений Романов,Санкт-Петербург,books,1480,paid,3,4
14,2015,Людмила Баранова,Казань,tech,3150,paid,4,4
15,2016,Матвей Соловьёв,Москва,office,760,paid,3,3
17,2018,Денис Куликов,Санкт-Петербург,home,2840,cancelled,0,0
18,2019,Татьяна Фролова,Москва,home,1940,paid,2,4
19,2020,Павел Казаков,Казань,tech,4250,paid,3,5
21,2022,Владимир Гусев,Москва,books,1680,paid,5,4
22,2023,Маргарита Орехова,Санкт-Петербург,tech,5350,paid,2,5
23,2024,Антон Быков,Казань,home,2050,paid,4,3
24,2025,Нина Данилова,Москва,office,610,cancelled,0,0
26,2027,Алёна Зайцева,Санкт-Петербург,books,1250,paid,5,5
27,2028,Борис Мартынов,Москва,home,2470,paid,2,4
28,2029,Оксана Котова,Казань,office,830,paid,6,4

In [74]:
orders[orders['amount'].between(1500,4000)]

,order_id,customer,city,category,amount,status,delivery_days,rating
0,2001,Дарья Мельникова,Москва,tech,3490,paid,2,5
3,2004,Артур Беляев,Москва,home,2290,paid,3,5
5,2006,Кирилл Громов,Казань,home,1750,paid,6,3
9,2010,Глеб Макаров,Москва,tech,2600,paid,1,5
11,2012,Степан Захаров,Самара,home,1980,paid,5,4
14,2015,Людмила Баранова,Казань,tech,3150,paid,4,4
17,2018,Денис Куликов,Санкт-Петербург,home,2840,cancelled,0,0
18,2019,Татьяна Фролова,Москва,home,1940,paid,2,4
21,2022,Владимир Гусев,Москва,books,1680,paid,5,4
23,2024,Антон Быков,Казань,home,2050,paid,4,3
25,2026,Ярослав Крылов,Самара,tech,3800,paid,3,4
27,2028,Борис Мартынов,Москва,home,2470,paid,2,4

# Задание №4. loc, iloc, категории и сортировка

## 4.1 iloc

Через iloc получите первые 5 строк и первые 4 столбца этих строк.

In [75]:
orders.iloc[0:5, 0:4]

   order_id          customer             city category
0      2001  Дарья Мельникова           Москва     tech
1      2002      Илья Воронов           Казань    books
2      2003     Полина Жукова           Самара   office
3      2004      Артур Беляев           Москва     home
4      2005      Елена Фомина  Санкт-Петербург     tech

# 4.2 loc

Через loc получите строки с индексами от 0 до 4 и только столбцы:

* customer  

* city  

* amount

In [76]:
orders.loc[0:4, ['customer','city','amount']]

           customer             city  amount
0  Дарья Мельникова           Москва    3490
1      Илья Воронов           Казань     990
2     Полина Жукова           Самара     650
3      Артур Беляев           Москва    2290
4      Елена Фомина  Санкт-Петербург    4890

# 4.3 Категории

Получите:

1. уникальные города;
2. количество уникальных городов;
3. количество заказов по категориям;
4. количество заказов по статусам.

In [77]:
orders['city'].unique()

array(['Москва', 'Казань', 'Самара', 'Санкт-Петербург'], dtype=object)

In [78]:
orders['city'].nunique()

4

In [79]:
orders['category'].value_counts()

category
tech      10
office     7
home       7
books      6
Name: count, dtype: int64

In [80]:
orders['status'].value_counts()

status
paid         26
cancelled     4
Name: count, dtype: int64

# 4.4 Сортировка

Создайте таблицу, в которой:

1. остаются только оплаченные заказы;
2. остаются только столбцы:
order_id, customer, city, category, amount
3. строки отсортированы по amount по убыванию;
4. индекс сброшен через:
reset_index(drop=True)

In [81]:
paid_orders = orders[orders['status'] == 'paid']
paid_orders = paid_orders[['order_id', 'customer', 'city', 'category', 'amount']]

paid_orders

    order_id             customer             city category  amount
0       2001     Дарья Мельникова           Москва     tech    3490
1       2002         Илья Воронов           Казань    books     990
2       2003        Полина Жукова           Самара   office     650
3       2004         Артур Беляев           Москва     home    2290
5       2006        Кирилл Громов           Казань     home    1750
6       2007     Валерия Тихонова           Москва    books    1350
7       2008         Олег Комаров           Самара     tech    5790
8       2009  Анастасия Савельева  Санкт-Петербург   office     870
9       2010         Глеб Макаров           Москва     tech    2600
11      2012       Степан Захаров           Самара     home    1980
12      2013      Ксения Миронова           Москва     tech    7200
13      2014      Евгений Романов  Санкт-Петербург    books    1480
14      2015     Людмила Баранова           Казань     tech    3150
15      2016      Матвей Соловьёв           Москва   office     760
16      2017     Вероника Власова           Самара    books    1120
18      2019      Татьяна Фролова           Москва     home    1940
19      2020        Павел Казаков           Казань     tech    4250
20      2021        Арина Маслова           Самара   office     920
21      2022       Владимир Гусев           Москва    books    1680
22      2023    Маргарита Орехова  Санкт-Петербург     tech    5350
23      2024          Антон Быков           Казань     home    2050
25      2026       Ярослав Крылов           Самара     tech    3800
26      2027        Алёна Зайцева  Санкт-Петербург    books    1250
27      2028       Борис Мартынов           Москва     home    2470
28      2029        Оксана Котова           Казань   office     830
29      2030        Фёдор Суворов           Самара     tech    6400

In [82]:
paid_orders.sort_values('amount', ascending = True).reset_index(drop=True)

    order_id             customer             city category  amount
0       2003        Полина Жукова           Самара   office     650
1       2016      Матвей Соловьёв           Москва   office     760
2       2029        Оксана Котова           Казань   office     830
3       2009  Анастасия Савельева  Санкт-Петербург   office     870
4       2021        Арина Маслова           Самара   office     920
5       2002         Илья Воронов           Казань    books     990
6       2017     Вероника Власова           Самара    books    1120
7       2027        Алёна Зайцева  Санкт-Петербург    books    1250
8       2007     Валерия Тихонова           Москва    books    1350
9       2014      Евгений Романов  Санкт-Петербург    books    1480
10      2022       Владимир Гусев           Москва    books    1680
11      2006        Кирилл Громов           Казань     home    1750
12      2019      Татьяна Фролова           Москва     home    1940
13      2012       Степан Захаров           Самара     home    1980
14      2024          Антон Быков           Казань     home    2050
15      2004         Артур Беляев           Москва     home    2290
16      2028       Борис Мартынов           Москва     home    2470
17      2010         Глеб Макаров           Москва     tech    2600
18      2015     Людмила Баранова           Казань     tech    3150
19      2001     Дарья Мельникова           Москва     tech    3490
20      2026       Ярослав Крылов           Самара     tech    3800
21      2020        Павел Казаков           Казань     tech    4250
22      2023    Маргарита Орехова  Санкт-Петербург     tech    5350
23      2008         Олег Комаров           Самара     tech    5790
24      2030        Фёдор Суворов           Самара     tech    6400
25      2013      Ксения Миронова           Москва     tech    7200

## Задание 5 Краткий вывод

Чем Series отличается от DataFrame?  

В чём разница между loc и iloc?  

Как связаны логические маски NumPy и фильтрация Pandas?  

Какой запрос к таблице оказался самым сложным и почему?

Series это одномернный массив данных, а DataFrame многомерный, чаще всего двумерный. Используя loc мы работаем по меткам индекса, а с iloc по позиции. Маски в numpy и pandas похожи по синтексису, но в pandas логическая маска уже переносится от массива к таблице. Для меня сложнее всего было написать запрос в задание 4, так как картинка в голове не складывалась, а я пытался уложить всё в одну строчку, в итоге разбил на несколько преобразований :)